[project]
name = "pygosym"
authors = [{name = "Victor Collod", email = "victor.collod@epita.fr"}]
dynamic = ["version", "description"]

[project.urls]
Home = "https://github.com/multun/pygosym"

[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"
